
// Multi-tenant Structure
export interface Tenant {
  id: string;
  name: string;
  domain: string;
  theme: {
    primaryColor: string;
    logoUrl: string;
  };
}

// User & Auth
export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  MEMBER = 'MEMBER',
  GUEST = 'GUEST'
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatarUrl: string;
  tenantId: string;
  // New fields for retention
  interests: string[]; // Generated by Wizard
  joinedDate: string;
  coverUrl?: string;
  phone?: string;
  city?: string;
  status?: 'Active' | 'Pending' | 'Blocked';
}

export interface UserActivity {
  id: string;
  type: 'Event' | 'Reading' | 'Donation' | 'Meditation';
  title: string;
  date: string;
  status: 'Completed' | 'Registered';
}

export interface ContentInteraction {
  id: string;
  userId?: string; // Optional if public
  assetId: string;
  assetName: string;
  assetType: string; // 'video', 'audio', 'document', 'Article', etc.
  tags: string[];
  timestamp: string;
}

// Wizard / AI Logic
export interface WizardOption {
  label: string;
  value: string;
  relatedTags: string[]; // Tags to assign to user
}

export interface WizardStep {
  id: number;
  question: string;
  options: WizardOption[];
}

// CMS Entities
export interface SEOConfig {
  title: string;
  description: string;
  keywords: string[];
  ogImage?: string;
  schemaType?: string; // e.g., 'Article', 'Event', 'Organization'
}

export interface ChangeLog {
  id: string;
  userId: string;
  userName: string;
  section: string; // e.g., 'Home > Hero', 'CMS > Article #12'
  action: 'Create' | 'Update' | 'Delete' | 'Rollback';
  timestamp: string;
  details: string;
  previousState?: string; // JSON stringified state for rollback
}

export interface ContentItem {
  id: string;
  title: string;
  type: 'Article' | 'Page' | 'Event' | 'Resource';
  status: 'Published' | 'Draft';
  author: string;
  publishDate: string;
  views: number;
  tags: string[];
  imageUrl?: string;
  seo?: SEOConfig;
}

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  imageUrl: string;
  date: string;
  author: string;
  content?: string; // Full HTML/Markdown content
  seo?: SEOConfig;
}

export interface BlogConfig {
  sectionTitle: string;
  sectionSubtitle: string;
  postsToShow: number;
  autoPlay: boolean;
  autoPlaySpeed: number;
  cardStyle: 'Standard' | 'Compact' | 'Minimal';
}

// HOME & FOOTER CONFIGURATION
export interface HomeThreeColumn {
  icon: string;
  title: string;
  description: string;
  link?: string;
  order: number;
  alignment: 'left' | 'center' | 'right';
}

export interface FooterColumn {
  title: string;
  links: { label: string; path: string; url?: string }[];
}

export interface FooterConfig {
  columns: FooterColumn[];
  socialLinks: { platform: string; url: string; icon: string }[];
  subscriptionTitle: string;
  subscriptionSubtitle: string;
  leadSourceTag: string; // Tag to identify lead origin in CRM
  copyright: string;
}

export interface HeroConfig {
  title: string;
  highlightWord: string;
  subtitle: string;
  backgrounds: HeroMedia[];
  modalVideoId: string;
  ctaText: string;
  ctaLink: string;
  sliderSpeed: number;
  showControls: boolean;
  textAlignment: 'left' | 'center' | 'right';
}

export interface SearchItem {
  label: string;
  icon: string;
  path: string;
}

export interface HomeConfig {
  hero: HeroConfig;
  searchSubtitle: string;
  searchItems: SearchItem[];
  threeColumns: HomeThreeColumn[];
  blogSection: BlogConfig;
  activitiesSection: {
    title: string;
    subtitle: string;
    maxEvents: number;
    order: number;
  };
  sectionOrder: string[]; // ['hero', 'search', 'threeColumns', 'blog', 'activities']
  footer: FooterConfig;
}

// DYNAMIC PAGES (WYSIWYG)
export interface PageSection {
  id: string;
  type: 'Text' | 'Image' | 'Gallery' | 'Stats' | 'Cards' | 'IconGrid' | 'Hero' | 'Video' | 'CTA' | 'Accordion' | 'ResourcesGrid' | 'EventsCalendar' | 'Timeline' | 'MethodPillars';
  content: any; // Flexible content based on type
  order: number;
  settings?: {
    backgroundColor?: string;
    padding?: 'small' | 'medium' | 'large';
    containerSize?: 'narrow' | 'standard' | 'full';
  };
}

export interface CustomPage {
  id: string;
  slug: string;
  title: string;
  status: 'Published' | 'Draft';
  sections: PageSection[];
  seo: SEOConfig;
}

// MEGA MENU
export interface MegaMenuColumn {
  title: string;
  items: { label: string; path: string; icon?: string; desc?: string }[];
}

export interface MegaMenuItem {
  label: string;
  path: string;
  description?: string;
  columns?: MegaMenuColumn[];
}

// MEET & ZOOM LOBBY
export interface EventResource {
  type: string; // PDF, Lectura, Video
  title: string;
  size?: string;
  url?: string;
}

export interface CalendarEvent {
  id: string;
  title: string;
  date: string;
  day: string;
  month: string;
  time: string;
  location: string;
  type: 'Presencial' | 'Online' | 'Híbrido';
  color: string;
  meetingUrl?: string;
  zoomId?: string;
  zoomPassword?: string;
  platform?: 'Zoom';          // Solo Zoom — regla de negocio
  agenda?: string[];          // Mantenido por compatibilidad
  resources?: EventResource[]; // Mantenido por compatibilidad
  seo?: SEOConfig;
  // --- Campos nuevos Módulo 1 (todos opcionales, sin romper nada) ---
  organizerContactId?: string;  // ID en db.crm
  mediaRefs?: MeetingMediaRef[];      // Refs a Biblioteca de Medios (solo lectura)
  agendaItems?: MeetingAgendaItem[];  // Agenda estructurada
  zoomWidgetConfig?: ZoomWidgetConfig;
  eventStatus?: 'Programada' | 'En curso' | 'Finalizada';
  linkedActivityId?: string;   // ID en ActivityEvent (sync M2→M1)
}

// HERO MEDIA
export interface HeroMedia {
  id: string;
  type: 'image' | 'video';
  url: string;
  alt?: string;
}

// CRM Entities

export interface ContactList {
  id: string;
  name: string;
  description: string;
  createdAt: string;
  contactCount?: number;
}

export interface Contact {
  id: string;
  name: string;
  firstName?: string;
  lastName?: string;
  email: string;
  phone: string;
  role: string;
  status: 'Subscribed' | 'Unsubscribed' | 'Bounced' | 'Pending' | 'new';
  lastContact: string;
  tags: string[];
  notes?: string;
  engagementScore?: number; // 0-100
  mailrelayId?: string; // ID in Mailrelay system
  city?: string;
  country?: string;
  createdAt?: string;
  listIds?: string[]; // Arrays of list IDs this contact belongs to
}

export interface EmailLog {
  id: string;
  contactId: string;
  subject: string;
  sentAt: string;
  status: 'Delivered' | 'Opened' | 'Clicked' | 'Bounced' | 'Failed' | 'Queued';
  openedAt?: string;
  clickedAt?: string;
  errorMessage?: string;
  campaignName?: string;
}

export interface EmailMetrics {
  totalSent: number;
  openRate: number;
  clickRate: number;
  bounceRate: number;
  history: { date: string; sent: number; opened: number; clicked: number }[];
}

export interface SMTPConfig {
  host: string;
  port: string;
  secure: boolean;
  user: string;
  pass: string;
  fromEmail: string;
  fromName: string;
}

// MEDIA LIBRARY
export interface MediaAsset {
  id: string;
  name: string;
  type: 'image' | 'video' | 'document' | 'audio';
  url: string;
  size: string;
  dimensions?: string;
  uploadedAt: string;
  tags: string[];
  folderId?: string;
}

export interface MediaFolder {
  id: string;
  name: string;
  parentId?: string;
}

export interface AutomationStats {
  sent: number;
  opened: number;
  clicked: number;
}

export interface AutomationWorkflow {
  id: string;
  name: string;
  trigger: string;
  status: 'Active' | 'Paused';
  stats: AutomationStats;
}

export interface NavItem {
  label: string;
  path: string;
  children?: NavItem[];
}

// --- EMAIL CAMPAIGNS ---
export interface Campaign {
  id: string;
  name: string;          // Internal campaign name
  subject: string;
  content: string;       // HTML content
  status: 'Draft' | 'Scheduled' | 'Sent' | 'Testing';
  recipientType: 'all' | 'subscribed' | 'list'; // Targeting strategy
  listId?: string;        // If recipientType === 'list'
  recipientCount: number; // Snapshot at send time
  createdAt: string;
  sentAt?: string;
  scheduledAt?: string;
  testEmail?: string;     // Last test email sent to
  metrics: {
    sent: number;
    opened: number;
    clicked: number;
    bounced: number;
  };
}

// ============================================================
// --- AUTOMATION ENGINE ---
// ============================================================

export type AutomationTriggerType =
  | 'contact_added_to_list'
  | 'tag_added'
  | 'campaign_sent'
  | 'campaign_opened'
  | 'campaign_clicked'
  | 'no_activity'
  | 'scheduled_date'
  | 'manual';

export interface AutomationTrigger {
  type: AutomationTriggerType;
  listId?: string;
  tag?: string;
  campaignId?: string;
  inactiveDays?: number;
  scheduledAt?: string;
}

export type AutomationNodeType =
  | 'send_email'
  | 'wait'
  | 'condition'
  | 'update_tag'
  | 'move_to_list'
  | 'end';

export interface SendEmailNode {
  id: string; type: 'send_email';
  subject: string;
  content: string;
  fromName?: string;
}

export interface WaitNode {
  id: string; type: 'wait';
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export interface ConditionNode {
  id: string; type: 'condition';
  check: 'email_opened' | 'email_clicked' | 'has_tag' | 'in_list';
  value?: string;
  branchTrue: AutomationNode[];
  branchFalse: AutomationNode[];
}

export interface UpdateTagNode {
  id: string; type: 'update_tag';
  action: 'add' | 'remove';
  tag: string;
}

export interface MoveToListNode {
  id: string; type: 'move_to_list';
  listId: string;
}

export interface EndNode {
  id: string; type: 'end';
}

export type AutomationNode =
  | SendEmailNode
  | WaitNode
  | ConditionNode
  | UpdateTagNode
  | MoveToListNode
  | EndNode;

export interface AutomationExecution {
  id: string;
  automationId: string;
  contactId: string;
  contactEmail: string;
  startedAt: string;
  completedAt?: string;
  currentStep: number;
  status: 'running' | 'completed' | 'failed';
  log: string[];
}

export interface AutomationRule {
  id: string;
  name: string;
  description?: string;
  status: 'Active' | 'Paused' | 'Draft';
  trigger: AutomationTrigger;
  nodes: AutomationNode[];
  nodePositions?: Record<string, { x: number; y: number }>;
  createdAt: string;
  updatedAt: string;
  stats: {
    totalExecutions: number;
    completed: number;
    emailsSent: number;
    tagsApplied: number;
  };
}

// ============================================================
// --- JOURNEY / PROFILE SYSTEM ---
// ============================================================

export interface WizardOptionEditable {
  id: string;
  label: string;
  value: string;
  profileTags: string[];
}

export interface WizardQuestion {
  id: string;
  order: number;
  question: string;
  subtitle?: string;
  options: WizardOptionEditable[];
  isActive: boolean;
}

export interface ProfileKitItem {
  id: string;
  title: string;
  type: 'PDF' | 'Audio' | 'Video' | 'Article' | 'Link';
  catalogItemId?: string;
  url?: string;
  description?: string;
}

/** A user profile archetype created by the admin */
export interface ProfileType {
  id: string;
  name: string;
  description: string;
  emoji: string;
  contentTags: string[];
  kitItems: ProfileKitItem[];
  crmTag: string;
  crmListId?: string;
  color: string;
}


/** Splash screen config shown after wizard completion */
export interface WizardSplashConfig {
  title: string;
  message: string;
  bgColor: string;
  bgType: 'color' | 'image' | 'video'; // Background mode
  bgImageUrl?: string;                  // Used when bgType === 'image'
  bgVideoUrl?: string;                  // Used when bgType === 'video'
  textColor: string;
  durationSeconds: number;
  redirectUrl: string;
}

/** Global wizard configuration */
export interface WizardConfig {
  splash: WizardSplashConfig;
  defaultCrmListId?: string;
  welcomeAutomationId?: string;
  isActive: boolean;
}

/** The profile assigned to a registered user after completing the wizard */
export interface UserWizardProfile {
  userId: string;
  profileTypeId: string;
  profileTypeName: string;
  wizardAnswers: Record<string, string>;
  derivedTags: string[];
  completedAt: string;
}

// ============================================================
// --- CONTENT CATALOG ---
// ============================================================

export interface ContentCatalogItem {
  id: string;
  title: string;
  description: string;
  type: 'PDF' | 'Audio' | 'Video' | 'Article' | 'External';
  mediaAssetId?: string;
  externalUrl?: string;
  thumbnailUrl?: string;
  duration?: string;
  tags: string[];
  targetProfiles: string[];
  isKitItem: boolean;
  access: 'public' | 'member';
  featured: boolean;
  order: number;
  publishedAt: string;
  status: 'draft' | 'published';
}

// ============================================================
// --- SITE SETTINGS ---
// ============================================================

export interface AdminUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  isActive: boolean;
  lastLogin?: string;
  createdAt: string;
}

export interface SiteSettings {
  siteName: string;
  siteDescription: string;
  siteUrl: string;
  logoUrl: string;
  faviconUrl: string;
  primaryColor: string;
  accentColor: string;
  timezone: string;
  language: string;
  maintenanceMode: boolean;
  socialLinks: {
    instagram?: string;
    facebook?: string;
    youtube?: string;
    whatsapp?: string;
    twitter?: string;
  };
  seoTitle: string;
  seoDescription: string;
  ogImageUrl?: string;
  gaId?: string;
  gtmId?: string;
  metaPixelId?: string;
  notificationEmail: string;
  notifyOnSubscribe: boolean;
  notifyOnBounce: boolean;
  notifyOnAutomationFail: boolean;
  weeklyDigest: boolean;
}

// ============================================================
// --- MÓDULO 1: SALA DE REUNIONES VIRTUALES (Zoom) ---
// ============================================================

/** Punto de agenda con duración estimada */
export interface MeetingAgendaItem {
  id: string;
  order: number;
  title: string;
  description?: string;
  durationMinutes: number;
}

/** Referencia a un asset de la Biblioteca de Medios. NUNCA se duplica ni modifica. */
export interface MeetingMediaRef {
  mediaAssetId: string;
  label?: string;
}

/** Configuración del widget Zoom visible en el perfil del miembro */
export interface ZoomWidgetConfig {
  subtitle: string;
  activityName: string;
  joinButtonText: string;
  zoomUrl: string;
}

/** Pregunta del cuestionario de feedback post-sesión */
export interface FeedbackQuestion {
  id: string;
  order: number;
  text: string;
  type: 'rating' | 'multiple_choice' | 'text';
  options?: string[];   // Solo para tipo multiple_choice
  isActive: boolean;
}

/** Respuesta de un miembro a un cuestionario post-sesión */
export interface FeedbackResponse {
  id: string;
  eventId: string;
  userId: string;
  userName: string;
  submittedAt: string;
  answers: {
    questionId: string;
    questionText: string;
    value: string | number;
  }[];
  overallRating: number;   // Promedio 1-5 para analytics
}

/** Tipos de reconocimiento en el sistema de gamificación */
export type BadgeType = 'estrella' | 'medalla_bronce' | 'medalla_plata' | 'medalla_oro' | 'especial';

/** Medalla/reconocimiento asignado a un miembro */
export interface MemberBadge {
  id: string;
  userId: string;
  type: BadgeType;
  label: string;
  reason: string;
  awardedAt: string;
  awardedBy: string;   // userId del admin que lo asignó
}

/** Registro de participación de un miembro en una actividad */
export interface ParticipationRecord {
  id: string;
  userId: string;
  eventId: string;
  eventTitle: string;
  participatedAt: string;
  feedbackSubmitted: boolean;
  feedbackBlocksNext: boolean;  // true si NO respondió → bloquea próxima actividad
}

// ============================================================
// --- MÓDULO 2: CALENDARIO DE ACTIVIDADES ---
// ============================================================

/** Categoría de actividad configurable desde admin */
export interface ActivityCategory {
  id: string;
  name: string;
  color: string;   // hex
  icon: string;    // nombre de ícono Lucide
}

/** Evento del calendario de actividades */
export interface ActivityEvent {
  id: string;
  title: string;
  description: string;       // HTML del editor rico del sistema
  category: string;          // ID de ActivityCategory
  tags: string[];
  startDate: string;         // YYYY-MM-DD
  endDate: string;
  startTime: string;         // HH:MM
  endTime: string;
  modality: 'Virtual' | 'Presencial' | 'Híbrida';
  organizerContactId?: string;
  status: 'Borrador' | 'Publicado' | 'Archivado';
  imageUrl?: string;
  seo?: SEOConfig;
  featuredInDashboard: boolean;  // Replica en "Novedades para Ti"
  // Sync bidireccional con Módulo 1 (solo si modality === 'Virtual')
  linkedMeetingId?: string;   // ID del CalendarEvent sincronizado
  zoomUrl?: string;
  createdAt: string;
  updatedAt: string;
}
